Repository maasu-org/maasu, pull requests merged in 2020-06, with the labels that each got.

#5 Small Breakpoint Promo Resizing
  .env
  .eslintrc
  .eslintrc.js
  .prettierrc
  README.md
  package.json
  src/react-app-env.d.ts
  src/site/Upcoming/SC.js
  src/site/Upcoming/SC.module.scss
  tsconfig.json
  yarn.lock
Labels: fix

#6 Workflow documentation
  README.md
  yarn.lock
Labels: documentation

#7 Refactor core name and upcoming strings to constants
  README.md
  src/constants/strings/core.ts
  src/constants/strings/index.ts
  src/constants/strings/upcoming.ts
  src/site/Upcoming/SC.js
Labels: refactor

#10 Logo update
  public/assets/branding/Logo-wSymbol.svg
  public/assets/branding/Logo.svg
  public/assets/branding/LogoSymbol.svg
  public/assets/branding/LogoVertical-AltDark.svg
  public/assets/branding/blm/logo-square.svg
  public/assets/branding/blm/logo-text.svg
  public/assets/branding/blm/logo.svg
  public/assets/branding/blm/text.svg
  public/assets/branding/dark/logo-square.svg
  public/assets/branding/dark/logo-text.svg
  public/assets/branding/dark/logo.svg
  public/assets/branding/dark/text.svg
  public/assets/branding/light/logo-square.svg
  public/assets/branding/light/logo-text.svg
  public/assets/branding/light/logo.svg
  public/assets/branding/light/text.svg
  public/assets/branding/mono/logo-square.svg
  public/assets/branding/mono/logo-text.svg
  public/assets/branding/mono/logo.svg
  public/assets/branding/mono/text.svg
  public/assets/branding/pride/logo-square.svg
  public/assets/branding/pride/logo-text.svg
  public/assets/branding/pride/logo.svg
  public/assets/branding/pride/text.svg
  public/assets/branding/trans/logo-square.svg
  public/assets/branding/trans/logo-text.svg
  public/assets/branding/trans/logo.svg
  public/assets/branding/trans/text.svg
  src/site/Alumni/index.js
  src/site/Contact/index.js
  src/site/Donate/index.js
  src/site/Mission/index.js
  src/site/Upcoming/LS.js
  src/site/Upcoming/SC.js
Labels: feature, refactor

#12 Documentation and Bugfixes
  README.md
  docs/board.md
  docs/intro.md
  package.json
  src/site/MaasuX/index.js
  yarn.lock
Labels: bug, documentation

#15 Content Width and Conflicts
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  package.json
  public/index.html
  src/_theme.js
  src/components/AspectRatioBox/AspectRatioBox.test.js
  src/components/AspectRatioBox/index.js
  src/components/BufferedImage/BufferedImage.test.js
  src/components/Grid/Cell.test.js
  src/components/Grid/index.js
  src/components/Page/index.js
  src/components/Timeline/Timeline.js
  src/components/Timeline/__tests__/Time.test.js
  src/components/Timeline/__tests__/Timeline.test.js
  src/components/Timeline/__tests__/TimelineSubtitle.test.js
  src/components/Timeline/__tests__/TimelineTitle.test.js
  src/components/Typography/Typography.test.js
  src/components/react-utility-components/Menu/Link.js
  src/components/react-utility-components/Menu/SubMenu.js
  src/components/react-utility-components/Menu/__tests__/Link.test.js
  src/components/react-utility-components/Menu/__tests__/Menu.test.js
  src/components/react-utility-components/Menu/__tests__/Submenu.test.js
  src/components/react-utility-components/Menu/index.js
  src/components/react-utility-components/Store/__tests__/Consumer.test.js
  src/components/react-utility-components/Store/__tests__/Provider.test.js
  src/components/react-utility-components/Store/index.js
  src/components/react-utility-components/index.js
  src/constants/core.ts
  src/containers/Board/index.js
  src/containers/Contact/index.js
  src/containers/FooterContainer.tsx
  src/containers/HeaderContainer.tsx
  src/containers/HeroBanner.tsx
  src/containers/History/index.js
  src/containers/Home/index.js
  src/containers/HomepageContainer.tsx
  src/containers/Mission/index.js
  src/containers/Upcoming/SC.js
  src/containers/Upcoming/index.js
  src/containers/WrapperMenu/WrapperMenu.test.js
  src/containers/WrapperMenu/index.js
  src/css/_def.scss
  src/css/legacy.scss
  src/css/media.scss
  src/css/styles.scss
  src/routes/routes.tsx
  utility.d.ts
  yarn.lock
Labels: feature, refactor

#16 HeroBanner styling, removing legacy styles, and media queries
  README.md
  public/assets/img/gold.gif
  public/assets/img/sky.jpg
  src/components/Page/index.js
  src/components/Timeline/Time.js
  src/components/Typography/index.js
  src/components/react-utility-components/Menu/Link.js
  src/containers/Alumni/index.js
  src/containers/ApiaOrgs/index.js
  src/containers/Awards/index.js
  src/containers/Board/index.js
  src/containers/Contact/index.js
  src/containers/DC/index.js
  src/containers/Donate/index.js
  src/containers/FooterContainer.tsx
  src/containers/HeroBanner.tsx
  src/containers/Host/index.js
  src/containers/MaasuX/index.js
  src/containers/Members/index.js
  src/containers/Mission/index.js
  src/containers/NewsLetter/index.js
  src/containers/PastAwards/index.js
  src/containers/PastConf/index.js
  src/containers/WhereAreYouFrom/index.js
  src/containers/WrapperMenu/index.js
  src/css/_def.scss
  src/css/functional.scss
  src/css/legacy.scss
  src/css/media.scss
  src/css/styles.scss
  src/utils/cookies.ts
Labels: refactor

#17 Align Mission with Annual Report
  src/containers/Mission/index.js
Labels: feature

#18 Documentation and Typescript Conversion Beginning
  README.md
  src/components/Page/index.js
  src/constants/mission.ts
  src/constants/strings.ts
  src/containers/Mission/index.js
  src/containers/MissionContainer.tsx
  src/containers/PastConf/index.js
  src/containers/__tests__/MissionContainer.test.js
  src/containers/index.js
  src/routes/routes.tsx
Labels: documentation, refactor

#19 Better utilities
  README.md
  src/containers/HeroBanner.tsx
  src/containers/InvalidRouteContainer.tsx
  src/containers/MissionContainer.tsx
  src/hooks/meta.ts
  src/routes/routes.tsx
  src/utils/files.ts
Labels: documentation, refactor

#20 Using Strings in Main Page Flows
  README.md
  public/fonts/Hind/Hind-Bold.woff
  public/fonts/Hind/Hind-Regular.woff
  public/fonts/Hind/OFL.txt
  public/fonts/hind-bold-modified/hind-bold-modified-webfont.woff
  public/fonts/hind-bold-modified/hind-bold-modified-webfont.woff2
  public/index.html
  src/constants/board.json
  src/constants/external.ts
  src/constants/history.json
  src/constants/mission.ts
  src/constants/pages.ts
  src/constants/strings.ts
  src/constants/upcoming.ts
  src/containers/Alumni/index.js
  src/containers/Awards/index.js
  src/containers/Board/index.js
  src/containers/Donate/index.js
  src/containers/HeroBanner.tsx
  src/containers/History/index.js
  src/containers/Host/index.js
  src/containers/Members/index.js
  src/containers/MissionContainer.tsx
  src/css/_def.scss
  src/css/functional.scss
  src/css/legacy.scss
  src/css/styles.scss
Labels: refactor

#21 Private Routing
  README.md
  src/constants/core.ts
  src/containers/MAAContainer.tsx
  src/routes/InvalidRoute.tsx
  src/routes/PrivateRoute.tsx
  src/routes/routes.tsx
Labels: feature

#22 Membership Fetching Sheets
  README.md
  netlify.toml
  package.json
  src/api/urls.ts
  src/components/Typography/index.js
  src/constants/cache/members.json
  src/constants/conferences.ts
  src/constants/history.json
  src/constants/strings.ts
  src/constants/upcoming.ts
  src/containers/HeroBanner.tsx
  src/containers/History/index.js
  src/containers/MAAContainer.tsx
  src/containers/Members/index.js
  src/containers/MembershipContainer.tsx
  src/containers/PastConf/index.js
  src/containers/WrapperMenu/index.js
  src/containers/__tests__/MembershipContainer.test.js
  src/containers/index.js
  src/css/styles.scss
  src/functions/src/__tests__/utils.test.js
  src/functions/src/members.ts
  src/functions/src/utils.ts
  src/functions/testHandler.js
  src/functions/tsconfig.json
  src/routes/routes.tsx
  src/store/types.ts
  yarn.lock
Labels: feature, refactor

#23 Redux and Conferences Function
  README.md
  package.json
  src/api/urls.ts
  src/constants/actions.ts
  src/constants/cache/members.json
  src/constants/core.ts
  src/constants/strings.ts
  src/containers/MembershipContainer.tsx
  src/functions/src/conferences.ts
  src/functions/src/members.ts
  src/functions/src/utils.ts
  src/index.tsx
  src/store/Members/actions.ts
  src/store/Members/reducers.ts
  src/store/Members/selectors.ts
  src/store/Members/types.ts
  src/store/api.ts
  src/store/reducers.ts
  src/store/store.ts
  src/store/types.ts
  yarn.lock
Labels: feature

#26 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation
